delete FROM mangos_zero_world.autobroadcast;

INSERT INTO `mangos_zero_world`.`autobroadcast` (`content`, `ratio`)
VALUES
('Nearby questgivers that are awaiting your return are shown as a mark on your mini-map.',1),
('Your spell casting can be cancelled by moving, jumping or hitting the escape key.',1),
('Clicking on a player name in the chat window lets you send a private message to them.',1),
('If you <Shift>Click on a player name in the chat window it tells you additional information about them.',1),
('You can <Control>-Click on an item to see how you would look wearing that item.',1),
('An item with its name in gray is a poor quality item and generally can be sold to a vendor.',1),
('An item with its name in white is useful to players in some way and can be used or sold at the auction house.',1),
('If you are lost trying to complete a quest, the quest log will often tell you what to do next.',1),
('You can send mail to other players or even to your other characters from any mailbox in game.',1),
('You can <Shift>-Click on an item to place an item link into a chat message.',1),
('You can remove a friendly spell enhancement on yourself by right-clicking on the spell effect icon.',1),
('When you learn a profession or secondary skill the button that allows you to perform that skill is found in the general tab of your spellbook.',1),
('All of your action bars can have their hotkeys remapped in the key bindings interface.',1),
('If a profession trainer cannot teach you any more, they will generally tell you where to go to get further training.',1),
('On your character sheet is a reputation tab that tells you your status with different groups.',1),
('You can use the Tab key to select nearby enemies in front of you.',1),
('If you are having trouble finding something in a capital city, try asking a guard for directions.',1),
('You can perform many fun actions with the emote system, for instance you can type /dance to dance.',1),
('You can only know two professions at a time, but you can learn all of the secondary skills (fishing, cooking and first-aid).',1),
('You can right-click on a beneficial spell that has been cast on you to dismiss it.',1),
('The interface options menu <ESC> has lots of ways to customize your game play.',1),
('You can turn off the slow scrolling of quest text in the interface options menu.',1),
('Spend your talent points carefully as once your talents are chosen, you must spend gold to unlearn them.',1),
('A mail icon next to the minimap means you have new mail. Visit a mailbox to retrieve it.',1),
('You can add additional action bars to your game interface from the interface options menu.',1),
('If you hold down <Shift> while right-clicking on a target to loot, you will automatically loot all items on the target.',1),
('Your character can eat and drink at the same time.',1),
('If you enjoyed playing with someone, put them on your friends list!',1),
('There are a number of different loot options when in a group. The group leader can right-click their own portrait to change the options.',1),
('You can choose not to display your helm and/or cloak with an option from the interface options menu.',1),
('You can target members of your party with the function keys. F1 targets you; F2 targets the second party member.',1),
('Being polite while in a group with others will get you invited back!',1),
('You can click on a faction in the reputation pane to get additional information and options about that faction.',1),
('A monster with a silver dragon around its portrait is a rare monster with better than average treasure.',1),
('If you mouse over a chat pane it will become visible and you can right-click on the chat pane tab for options.',1),
('You can display the duration of beneficial spells on you from the interface options menu.',1),
('You can lock your action bar so you don''t accidentally move spells. This is done using the interface options menu.',1),
('You can assign a Hotkey to toggle locking/unlocking your action bar. Just look in the Key Bindings options to set it.',1),
('You can cast a spell on yourself without deselecting your current target by holding down <Alt> while pressing your hotkey.',1),
('Ensure that all party members are on the same stage of an escort quest before beginning it.',1),
('You''re much less likely to encounter wandering monsters while following a road.',1),
('Killing guards gives no honor.',1),
('You can hide your interface with <Alt>-Z and take screenshots with <Print Screen>.',1),
('Typing /macro will bring up the interface to create macros.',1),
('Enemy players whose names appear in gray are much lower level than you are and will not give honor when killed.',1),
('From the Raid UI you can drag a player to the game field to see their status or drag a class icon to see all members of that class.',1),
('A blue question mark above a quest giver means the quest is repeatable.',1),
('Use the assist button (F key) while targeting another player, and it will target the same target as that player.',1),
('<Shift>-Clicking on an item being sold by a vendor will let you select how many of that item you wish to purchase.',1),
('If you are having trouble fishing in an area, try attaching a lure to your fishing pole.',1),
('You can view messages you previously sent in chat by pressing <Alt> and the up arrow key.',1),
('You can Shift-Click on an item stack to split it into smaller stacks.',1),
('Pressing both mouse buttons simultaneously will make your character run.',1),
('When replying to a tell from a player (Default ''R''), the <TAB> key cycles through people you have recently replied to.',1),
('Clicking an item name that appears bracketed in chat will tell you more about the item.',1),
('It''s considered polite to talk to someone before inviting them into a group, or opening a trade window.',1),
('Pressing ''v'' will toggle the display of a health bar over nearby enemies.',1),
('Your items do not suffer durability damage when you are killed by an enemy player.',1),
('<Shift>-click on a quest in your quest log to toggle quest tracking for that quest.',1),
('Quests completed at maximum level award money instead of experience.',1),
('<Shift>-B will open all your bags at once.',1),
('When interacting with other players a little kindness goes a long way!',1),
('Bring your friends to Azeroth, but don''t forget to go outside Azeroth with them as well.',1),
('If you keep an empty mailbox, the mail icon will let you know when you have new mail waiting!',1),
('Never give another player your account information.',1),
('When a player not in your group damages a monster before you do, it will display a gray health bar and you will get no loot or experience from killing it.',1),
('You can see the target of your current target by turning on the ''Show Target of Target'' option in the advanced interface options tab.',1),
('You can access the map either by clicking the map button in the upper left of the mini-map or by hitting the ''M'' key.',1),
('Spend your honor points for powerful rewards at the Champion''s Hall (Alliance) or Hall of Legends (Horde).',1),
('Quest items that are in the bank cannot be used to complete quests.',1),
('A quest marked as (Failed) in the quest log can be abandoned and then reacquired from the quest giver.',1),
('The number next to the quest name in your log is how many other party members are on that quest.',1),
('You cannot advance quests other than (Raid) quests while you are in a raid group.',1),
('You cannot cancel your bids in the auction house so bid carefully.',1),
('To enter a chat channel, type /join [channel name] and /leave [channel name] to exit.',1),
('Mail will be kept for a maximum of 30 days before it disappears.',1),
('Once you get a key, they can be found in a special key ring bag that is to the left of your bags.',1),
('City Guards will often give you directions to other locations of note in the city.',1),
('You can repurchase items you have recently sold to a vendor from the buyback tab.',1),
('A group leader can reset their instances from their portrait right-click menu.',1),
('You can always get a new hearthstone from any Innkeeper.',1),
('You can open a small map of the current zone either with Shift-M or as an option from the world map.',1),
('Players cannot dodge, parry, or block attacks that come from behind them.',1),
('If you Right Click on a name in the combat log a list of options will appear.',1),
('Creatures cannot make critical hits with spells, but players can.',1),
('Creatures can dodge attacks from behind, but players cannot. Neither creatures nor players can parry attacks from behind.',1),
('Don''t stand in the fire!',1),
('The Raid UI can be customized in a number of different ways, such as how it shows debuffs or current health.',1),
('Dungeons are more fun when everyone works together as a team. Be patient with players who are still learning the game.',1)
;
